services:
  jwt:
    image: jwt
    container_name: jwt
    pull_policy: never
    build: ./jwt
    expose:
      - ${JWT_PORT}
    ports:
      - "${JWT_PORT}:${JWT_PORT}"
    networks:
      - postgresdb_network
    depends_on:
      db:
        condition: service_healthy
      auth:
        condition: service_started
    tty: true
    init: true
    restart: always
    volumes:
      - ./jwt:/server
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - WEBSOCKET_WORKER=${WEBSOCKET_WORKER}
      - WEBSOCKET_THREAD=${WEBSOCKET_THREAD}
      - JWT_PORT=${JWT_PORT}
      - TWOFA_URL=${TWOFA_URL}
      - AI_USERID=${AI_USERID}
      - JWT_EXPIRE_SECONDS=${JWT_EXPIRE_SECONDS}
      - JWT_REFRESH_EXPIRE_SECONDS=${JWT_REFRESH_EXPIRE_SECONDS}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_AI_EXPIRE_SECONDS=${JWT_AI_EXPIRE_SECONDS}
      - FRONTEND_URL=${FRONTEND_URL}
  websocket:
    image: websocket
    container_name: websocket
    pull_policy: never
    build: ./websocket
    expose:
      - ${ROOM_PORT}
    ports:
      - "${ROOM_PORT}:${ROOM_PORT}"
    networks:
      - postgresdb_network
    depends_on:
      db:
        condition: service_healthy
      auth:
        condition: service_started
    tty: true
    init: true
    restart: always
    volumes:
      - ./websocket:/server
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - WEBSOCKET_WORKER=${WEBSOCKET_WORKER}
      - WEBSOCKET_THREAD=${WEBSOCKET_THREAD}
      - ROOM_PORT=${ROOM_PORT}
      - JWT_URL=${JWT_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - GAME_URL=${GAME_URL}
      - USER_URL=${USER_URL}
  game:
    image: game
    container_name: game
    pull_policy: never
    build: ./game
    expose:
      - ${GAME_PORT}
    ports:
      - "${GAME_PORT}:${GAME_PORT}"
    networks:
      - postgresdb_network
    depends_on:
      db:
        condition: service_healthy
      auth:
        condition: service_started
    tty: true
    init: true
    restart: always
    volumes:
      - ./game:/server
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - WEBSOCKET_WORKER=${WEBSOCKET_WORKER}
      - WEBSOCKET_THREAD=${WEBSOCKET_THREAD}
      - GAME_PORT=${GAME_PORT}
      - USER_URL=${USER_URL}
      - JWT_URL=${JWT_URL}
      - GAME_URL=${GAME_URL}
      - GAMEAI_URL=${GAMEAI_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - WINNING_SCORE=${WINNING_SCORE}
  game-ai:
    image: game-ai
    container_name: game-ai
    pull_policy: never
    build: ./game_ai
    expose:
      - ${GAMEAI_PORT}
    ports:
      - "${GAMEAI_PORT}:${GAMEAI_PORT}"
    networks:
      - postgresdb_network
    depends_on:
      db:
        condition: service_healthy
      game:
        condition: service_started
      auth:
        condition: service_started
    tty: true
    init: true
    restart: always
    volumes:
      - ./game_ai:/server
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - WEBSOCKET_WORKER=${WEBSOCKET_WORKER}
      - WEBSOCKET_THREAD=${WEBSOCKET_THREAD}
      - GAMEAI_PORT=${GAMEAI_PORT}
      - JWT_URL=${JWT_URL}
      - GAME_URL=${GAME_URL}
      - FRONTEND_URL=${FRONTEND_URL}
  auth:
    image: auth
    container_name: auth
    pull_policy: never
    build: ./auth
    expose:
      - ${AUTH_PORT}
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    networks:
      - postgresdb_network
    depends_on:
      db:
        condition: service_healthy
    tty: true
    init: true
    restart: always
    volumes:
      - ./auth:/server
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - WEBSOCKET_WORKER=${WEBSOCKET_WORKER}
      - WEBSOCKET_THREAD=${WEBSOCKET_THREAD}
      - AUTH_PORT=${AUTH_PORT}
      - FORTY_TWO_API_URL=${FORTY_TWO_API_URL}
      - OAUTH_42_URL=${OAUTH_42_URL}
      - OAUTH_TOKEN_URL=${OAUTH_TOKEN_URL}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI}
      - JWT_URL=${JWT_URL}
      - TWOFA_URL=${TWOFA_URL}
      - USER_URL=${USER_URL}
      - FRONTEND_URL=${FRONTEND_URL}
  twofa:
    image: twofa
    container_name: twofa
    pull_policy: never
    build: ./twofa
    expose:
      - ${TWOFA_PORT}
    ports:
      - "${TWOFA_PORT}:${TWOFA_PORT}"
    networks:
      - postgresdb_network
    depends_on:
      db:
        condition: service_healthy
      auth:
        condition: service_started
    tty: true
    init: true
    restart: always
    volumes:
      - ./twofa:/server
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - WEBSOCKET_WORKER=${WEBSOCKET_WORKER}
      - WEBSOCKET_THREAD=${WEBSOCKET_THREAD}
      - TWOFA_PORT=${TWOFA_PORT}
      - OTP_SECRET=${OTP_SECRET}
      - OTP_ISSUER=${OTP_ISSUER}
      - FRONTEND_URL=${FRONTEND_URL}
      - VALID_WINDOW=${VALID_WINDOW}
  user:
    init: true
    image: user
    build: ./user
    container_name: user
    restart: always
    depends_on:
      db:
        condition: service_healthy
      auth:
        condition: service_started
    networks:
      - postgresdb_network
    ports:
      - "${USER_PORT}:${USER_PORT}"
    volumes:
      - ./user/server:/server
      - media-data:/usr/share/nginx/html/media
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_URL=${JWT_URL}
      - USER_PORT=${USER_PORT}
      - FRONTEND_URL=${FRONTEND_URL}

  db:
    image: postgres:17.1-alpine3.20
    container_name: postgresdb
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    expose:
      - ${DB_PORT}
    networks:
      - postgresdb_network
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER}'"]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    init: true
    ports:
      - 443:443
    networks:
      - postgresdb_network
    volumes:
      - ./nginx/cert:/cert
      - ../frontend:/usr/share/nginx/html
      - media-data:/usr/share/nginx/html/media
    depends_on:
      - auth
      - game
      - game-ai
      - websocket
      - jwt
      - twofa
      - user
    environment:
      - KEY_FILEPATH=${KEY_FILEPATH}
      - CRT_FILEPATH=${CRT_FILEPATH}
      - SERVER_NAME=${SERVER_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - AUTH_PORT=${AUTH_PORT}
      - JWT_PORT=${JWT_PORT}
      - ROOM_PORT=${ROOM_PORT}
      - GAME_PORT=${GAME_PORT}
      - TWOFA_PORT=${TWOFA_PORT}
      - USER_PORT=${USER_PORT}

networks:
  postgresdb_network:
    driver: bridge

volumes:
  postgresql-data:
  media-data:
